Rewsly/config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'

  get 'stories/popular' => 'stories#popular'
  
  resources :stories
  

end

Rewsly/app/models/story.rb
class Story < ActiveRecord::Base
	validates :title, :url, :category, :upvotes, presence: true

  def self.search_for(query)                                                       
      where('title LIKE :query OR category LIKE :query', :query => "%#{query}%") 
  end    

  def self.popular
      where('upvotes > 5') 
  end
end

Rewsly/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rewsly/app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def index
    if params[:q]
      @stories = Story.search_for(params[:q]) 
    else
      @stories = Story.all
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new( story_params )
    if @story.save
      redirect_to @story
    else
      render :new
    end
  end

  def popular
    @stories = Story.popular
    render :index
  end

  private

  def story_params
    params.require(:story).permit(:title, :url, :category, :upvotes)
  end
  
end

Rewsly/app/helpers/application_helper.rb
module ApplicationHelper
end

Rewsly/app/helpers/stories_helper.rb
module StoriesHelper
end

Rewsly/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Rewsly/app/views/stories/index.html.erb
<h1>Welcome to Rewsly!</h1>

<%= form_tag "/", method: "GET" do %>
  <%= text_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<%= link_to 'Create New', new_story_path %>
<%= link_to 'Popular', stories_popular_path %>

<% @stories.each do |story| %>
  <h2><%= link_to story.title, story_path( story ) %></h2>
<% end %>

Rewsly/app/views/stories/new.html.erb
<%= form_for @story do |s| %>
<% if @story.errors.any? %>
  <h2>There were errors saving your story</h2>
  <ul>
    <% @story.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <p>
  <%= s.label :title %> 
  <%= s.text_field :title %> 
  </p>
  
  <p>
  <%= s.label :category %> 
  <%= s.text_field :category %> 
  </p>
  
  <p>
  <%= s.label :upvotes %> 
  <%= s.number_field :upvotes %> 
  </p>
  
  <p>
  <%= s.label :url %> 
  <%= s.url_field :url %> 
  </p>
  
  <p>
  <%= s.submit %>
  </p> 
<% end %>

Rewsly/app/views/stories/show.html.erb
<h2><%= @story.title %></h2>

<h3>Upvotes: <%= @story.upvotes %></h3>
<h3>Category: <%= @story.category %></h3>
<h3>Link: <%= link_to @story.url, @story.url %></h3>